"""Removed NOT NULL constraint from timestamp in AssetPrice model

Revision ID: 8fc3489641f3
Revises: d2727238c940
Create Date: 2022-08-21 01:35:30.827106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc3489641f3'
down_revision = 'd2727238c940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_prices', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               nullable=True)

    # If you are using SQLite you may need to replace the lines above and use
    # the following code:
    #
    # with op.batch_alter_table("assets_prices") as batch_op:
    #     batch_op.alter_column('timestamp',
    #         existing_type=sa.TIMESTAMP(),
    #         nullable=True)

    # You may want to "vaccum" your DB after it.
    #
    # with op.get_context().autocommit_block():
    #   op.execute("VACUUM")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_prices', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
