"""First revision

Revision ID: d2727238c940
Revises: 
Create Date: 2020-11-15 16:22:33.817297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2727238c940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_id', sa.String(length=32), nullable=False),
    sa.Column('asset_code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(scale=3), nullable=True),
    sa.Column('pct_factor', sa.Numeric(scale=3), nullable=True),
    sa.Column('emission_value', sa.Numeric(scale=3), nullable=True),
    sa.Column('date_of_approval', sa.DateTime(), nullable=True),
    sa.Column('date_of_record', sa.DateTime(), nullable=True),
    sa.Column('date_of_payment', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_id')
    )
    op.create_table('assets_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_id', sa.String(length=32), nullable=False),
    sa.Column('asset_code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.Numeric(scale=2), nullable=True),
    sa.Column('high', sa.Numeric(scale=2), nullable=True),
    sa.Column('low', sa.Numeric(scale=2), nullable=True),
    sa.Column('close', sa.Numeric(scale=2), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('variation', sa.Numeric(scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets_prices')
    op.drop_table('assets_earnings')
    # ### end Alembic commands ###
